### ISSUE TITLE
EventForwarder doesn't work unless installed directly on app?

### ISSUE THREAD

**Issue by DeeWBee** [mparticle-integrations/mparticle-javascript-integration-google-analytics#16]
Howdy! I'm a developer for SportsEngine and had a question/concern regarding the GAEventForwarder. The title of this post pretty much sums it up. 

Initially, I had installed the GAKit directly on a web-app (`npm i @mparticle....`). Combined with the base web-sdk, I was able to successfully send events to mParticle, and have them be forwarded onto GoogleAnalytics. 

_However_, I've since been developing an in-house NPM package - `se-mparticle` - with the end goal of distributing mParticle across various apps in our platform. `se-mparticle` has the base web-sdk and the GAKit listed as dependencies. When I install `se-mparticle` _on the same web-app as mentioned earlier_, I am able to successfully send events to mParticle, identify a user, and my cookieSync integration is working as expected. However, I am no longer able to forward events to GoogleAnalytics. I was wondering if you guys might have any ideas as to why that's the case. 

My top theory was that `se-mparticle` doesn't have access to the appropriate GoogleAnalytics tracking cookies, but if cookieSync is working on initialization... wouldn't Google Analytics work as well? Any insight is appreciated. Thanks!

**Comment by DeeWBee** [comment]
Update: Does _NOT_ appear to be cookie related. It looks like the call to Google to load the analytics script just isn't made...

**Comment by DeeWBee** [comment]
Second update: Figured out the issue. Was importing `@mparticle/web-google...` before `@mparticle/web-sdk`.

**Comment by rmi22186** [comment]
Hi @DeeWBee - glad you sorted it out! I was just about to respond.  The order or importing _shouldn't_ matter if you register the kit on the mParticle configuration object properly.

**Comment by DeeWBee** [comment]
@rmi22186 I was under the impression we were registering w/the config correctly. Here is the working code 

```
import mParticle from '@mparticle/web-sdk'
import * as gaKit from '@mparticle/web-google-analytics-kit'

  public init(currentUser: SeMParticleCurrentUser): void {
    mParticle.init(API_KEY, this.getConfig(currentUser))
    gaKit.register(this.getConfig(currentUser))
  }

  private getConfig(currentUser: SeMParticleCurrentUser): MParticleConfig {
    return {
      isDevelopmentMode: true,
      // useCookieStorage: true,
      identifyRequest: {
        userIdentities: { email: currentUser.email.address, customerid: currentUser.uuid }
      },
      identityCallback: (result: any) => this.identityCallback(result, Object.keys(currentUser.roles))
    }
  }
```

The only difference between working and not working is the order in which we imported the kits. Like I said, this is all in an in-house NPM package (written in typescript).

**Comment by rmi22186** [comment]
I'll bet if you reverse the init and kit registration order as follows, then the import order won't matter.
```
  public init(currentUser: SeMParticleCurrentUser): void {
    mParticle.init(API_KEY, this.getConfig(currentUser))
    gaKit.register(this.getConfig(currentUser))
  }
```
to be 
```
  public init(currentUser: SeMParticleCurrentUser): void {
    gaKit.register(this.getConfig(currentUser))
    mParticle.init(API_KEY, this.getConfig(currentUser))
}
```

All kits should be registered **before** initializing mParticle, as shown [here](https://docs.mparticle.com/developers/sdk/web/self-hosting/#full-initialization-examples). 

Please confirm.

**Comment by DeeWBee** [comment]
@rmi22186 My apologies, I mis-copied our code. We did in fact call `register` before `init`. But we were still encountering issues until we imported `mParticle` first.
